### ISSUE TITLE
Scene grid orientation would be more usable as vertical

### ISSUE THREAD

**Issue by robepstein** [MediaBrowser/Emby.Theater.Windows#214]
When navigating the scene list it's awkward scrolling horizontally to browse the sequence of scenes. Instead of displaying as:
1 2 3
4 5 6
It would make more sense to display as:
1 3 5
2 4 6
Or is it just me?
I have this change ready to commit if I can get agreement on the change.

**Comment by LukePulverenti** [comment]
No longer applicable.
