### ISSUE TITLE
Play queue management

### ISSUE THREAD

**Issue by TomGillen** [MediaBrowser/Emby.Theater.Windows#243]
The playback manager contains a [play queue](https://github.com/MediaBrowser/MediaBrowser.Theater/blob/2d82c0d1a649caceb8246df5f885806001e2518d/MediaBrowser.Theater/MediaBrowser.Theater.Playback/PlayQueue.cs) which allows mixed-content items to be added and removed from the queue at any time, and for the queue's shuffle and repeat mode to be changed during playback.

There is currently no way for the user to view and manage the play queue. There should be some way for the user to call up the list of queue'd items (from the playback OSD perhaps). From there, they should be able to toggle shuffle on/off, change the repeat mode to none/single/all, skip to an item, remove an item from the queue, or clear the queue.

There should also be new [`ItemCommands`](https://github.com/MediaBrowser/MediaBrowser.Theater/blob/2d82c0d1a649caceb8246df5f885806001e2518d/MediaBrowser.Theater/MediaBrowser.Theater.Api/Commands/ItemCommands/IItemCommand.cs) for queuing an item into the play queue, rather than starting immediately, which correspond to the [`PlayItemCommand`](https://github.com/MediaBrowser/MediaBrowser.Theater/blob/2d82c0d1a649caceb8246df5f885806001e2518d/MediaBrowser.Theater/MediaBrowser.Theater.Api.Implementations/Commands/ItemCommands/PlayItemCommand.cs) and [`PlayFromStartItemCommand`](https://github.com/MediaBrowser/MediaBrowser.Theater/blob/2d82c0d1a649caceb8246df5f885806001e2518d/MediaBrowser.Theater/MediaBrowser.Theater.Api.Implementations/Commands/ItemCommands/PlayFromStartItemCommand.cs).

**Comment by shaunarundell** [comment]
this is the sort of thing I could do easily to get back into the code base
