### ISSUE TITLE
MPDN errors not elegantly handled

### ISSUE THREAD

**Issue by TomGillen** [MediaBrowser/Emby.Theater.Windows#246]
If MPDN encounters an error, which may cause a popup message box, but does not close the app, Theater is unaware of the problem and it becomes impossible to close MPDN or start a new playback session.

**Comment by zachsaw** [comment]
Let me know if you need MPDN to allow you to pipe all errors to the extensions API and suppress error message box from being shown.

**Comment by LukePulverenti** [comment]
Hi Zach,
Thanks for reaching out. We are currently not using MPDN in favor of a homemade direct show based player. I will definitely reach out if that ever changes though. Thanks.
