### ISSUE TITLE
subtitles don't load automatically (small logic bug)

### ISSUE THREAD

**Issue by amitbet** [MediaBrowser/Emby.Theater.Windows#256]
There is a bug in the logics that select the subtitle stream, which causes the "no subtitle" stream to be selected every time (unless it doesn't exist)
[didn't think forking and requesting would be proper for a one character fix...]

There should be a not (!) before:
i.Name.ToLower().Contains("...

in DirectShowPlayer: 
  public void SetSubtitleStreamIndex(int subtitleStreamIndex)
...
                    .FirstOrDefault(i => i.Type == MediaStreamType.Subtitle && i.Name.ToLower().Contains("no 
...

In any case, Emby rulz! you are all doing an excellent work (Kodi is -bleep- every time i test it)
Amit.

**Comment by LukePulverenti** [comment]
Thanks, glad to hear it!

**Comment by LukePulverenti** [comment]
Hi, thanks. Are you sure about this? If the desired index is -1 then that means we want to turn off subtitles:

https://github.com/MediaBrowser/Emby.Theater.Windows/blob/master/Emby.Theater.DirectShow/DirectShowPlayer.cs#L3033-L3042

**Comment by amitbet** [comment]
The right fix may be in a different location,  but after trying everything, I wasn't able yo see subs (the srt file was always loaded but hidden in vobsub = i could turn it on via tray icon) this fixed my problem... My guess is that it always picks "no sub"  seeing that it always comes first - since as you said it's -1, so it never allows anything else to be selected.

**Comment by LukePulverenti** [comment]
Thanks, closing this then.
