### ISSUE TITLE
Audio track selection not working.

### ISSUE THREAD

**Issue by swhitmore** [MediaBrowser/Emby.Theater.Windows#265]

**Comment by swhitmore** [comment]
Reported as resolved.

**Comment by xzener** [comment]
Yes, you could change the audio stream... But the previous stream would be selected and couldn't be changed back. For example, my Blurays play primary HD audio, I can select the other embedded audio which does work... But if you go back to re-enable the primary audio, the check mark was already there, and you couldn't change the audio back. Should this be another bug report??
