### ISSUE TITLE
Navigation sounds stop after playing video

### ISSUE THREAD

**Issue by swhitmore** [MediaBrowser/Emby.Theater.Windows#273]
As per user post:

"Setup using hdmi audio passthru. after starting ET remote keytones are heard when navigating. after playing a video content, keytones are surpressed"

**Comment by xzener** [comment]
I've seen this too... Usually in-app audio works again after navigating around a bit. Although I have seen where it quits all together too. Its not persistent, but does happen. I blame my Onkyo Receiver.

**Comment by LukePulverenti** [comment]
This is an issue in Chromium and is out of our control. I am looking at how I can report it. Thanks.
