### ISSUE TITLE
When bitstreaming, files with TrueHD sound don't play

### ISSUE THREAD

**Issue by swhitmore** [MediaBrowser/Emby.Theater.Windows#275]
Presumably related to the cant that I can't bitstream truehd but the lav filters for my existing theater install are configured to accommodate that.

**Comment by xzener** [comment]
TrueHD bitstreams to my AVR without issue.

**Comment by wints66** [comment]
Yeah having the same issue here too, if I turn bitstream option off then they play. This is whilst using below options in ET
Bitstream = HDMI
Audio = Reclock
Video = madVR

**Comment by xzener** [comment]
Reclock seems to be the culprit. How can we narrow this down further and fix it?? Could it be related to video cards??

**Comment by LukePulverenti** [comment]
Reclock includes an alternative wasapi renderer. See if it exhibits the same issues.

**Comment by wints66** [comment]
I found enabling "Accept bitstream formats" in Reclock then everything works

**Comment by LukePulverenti** [comment]
Well done.
