### ISSUE TITLE
Remote stops functioning when background video is playing.

### ISSUE THREAD

**Issue by swhitmore** [MediaBrowser/Emby.Theater.Windows#277]
Using the official media centre remote, when entering a TV series you lose all functionality of the remote when the background theme video is playing.  Grab a keyboard to push up or down on keyboard resolves it.    Any TV series without a theme video doesn't have this issue.

**Comment by xzener** [comment]
I have a Harmony setup with MCE remote functionality... I have not seen this issue.

**Comment by LukePulverenti** [comment]
I can't reproduce this.
