### ISSUE TITLE
Lost app focus after screensaver loaded.

### ISSUE THREAD

**Issue by swhitmore** [MediaBrowser/Emby.Theater.Windows#278]
I lost focus after the screensaver kicked in. Couldn't use direction keys on keyboard, or remotes. Had to use the mouse to give something focus. Screen saver was just black - guess it was my windows screensaver and not Emby Theater's. Shouldn't Emby Theater prevent windows screensaver, and just use its own one?

**Comment by xzener** [comment]
I think maybe focus was set to the upper right of the screen. I've seen this before, a couple down clicks and focus was returned. Also, the light grey focus indicators for search/user/etc may be why this is being reported. Suggest defaulting focus to large tile (home screen), first media poster/cover (views), and the play button (details screen) after the screensaver is deactivated.

**Comment by LukePulverenti** [comment]
Should no longer be an issue.
