### ISSUE TITLE
Cannot close app during playback.

### ISSUE THREAD

**Issue by swhitmore** [MediaBrowser/Emby.Theater.Windows#283]
Clicking the standard Windows UI close button (X in the top right corner) during video playback does nothing. You have to manually stop the video before you can close the application. Furthermore, if you click the X to close the window before clicking the pause button to stop playback, the pause button often because unresponsive.

**Comment by xzener** [comment]
Ive seen this issue too. Pressing the "X" while the movie is playing dropped me back to the details screen. The movie (audio) continued to play. Unable to stop/close the app at that point. Had to kill the app from the task manager.
