### ISSUE TITLE
Pause / Play via remote not working

### ISSUE THREAD

**Issue by swhitmore** [MediaBrowser/Emby.Theater.Windows#287]

**Comment by xzener** [comment]
I can confirm this issue. I have a Harmony remote... Play/pause buttons do not seem to work during movie playback. Using keyboard (Spacebar) and mouse (OSD buttons) seem to be working fine.

**Comment by xzener** [comment]
Ok, we're half there... Play works now, but the pause button is still inop. Play actually pauses/plays with button presses.

**Comment by xzener** [comment]
@LukePulverenti Why is this closed?? The MCE pause button does not work.

**Comment by LukePulverenti** [comment]
Tested, no problem found.

**Comment by xzener** [comment]
Its not working here.

**Comment by xzener** [comment]
Issue on my end. Pause working on less complicated setup. ;)
