### ISSUE TITLE
Next up and Resume episode from home screen should go to episode list not the details screen

### ISSUE THREAD

**Issue by swhitmore** [MediaBrowser/Emby.Theater.Windows#299]

**Comment by bartonnen** [comment]
This would allow continuation to the next episode of the same series. Currently the user has to return to the home screen and then navigate back down to the series / season / episode to get to the next episode.

Some way of navigating from the episode detail screen to the next episode would be a good compromise. (EMC has this functionality - i.e. can navigate to next or previous episode from the episode detail screen).

**Comment by LukePulverenti** [comment]
I think people will just complain about extra clicks if next up brings you to the list screen. Now that we have automatic autoplay, i think that is the best option. What we need is what bartonned said above + a "coming up next" display near the end of the video.
