### ISSUE TITLE
Genres are Incorrect

### ISSUE THREAD

**Issue by xzener** [MediaBrowser/Emby.Theater.Windows#303]
If you go to movie genres, then select "more" (animation for example), the view is riddled with a plethora of different movie genres.
![capture](https://cloud.githubusercontent.com/assets/3745669/12254541/bb8c2b3a-b89e-11e5-802b-de58ecdf91c9.PNG)

**Comment by LukePulverenti** [comment]
It's using new api features that are only in dev. This issue will fix itself as those features get bumped to beta and stable.
