### ISSUE TITLE
Tagline Not Working

### ISSUE THREAD

**Issue by xzener** [MediaBrowser/Emby.Theater.Windows#304]
Some users are experiencing an issue where the have a tagline in the movie.xml... But the app is showing the movie title instead. 

http://emby.media/community/index.php?/topic/29774-new-version-testing/?p=286051

This particular user says one media library displays the tagline while another displays the title. AdrianW is also experiencing this issue.

**Comment by LukePulverenti** [comment]
Server issue. Not the app's problem.
