### ISSUE TITLE
Most srt subtitles not working

### ISSUE THREAD

**Issue by justpig** [MediaBrowser/Emby.Theater.Windows#310]
I have tried different videos, all .mkvs. It seems to mainly display pgssub and .srts with a letter in bracket like this (D) but other .srts will not display.

**Comment by justpig** [comment]
I have done a series of tests and this seems to be the issue with subtitles. The player only displays subtitles that are set to default in the metadata, any external subtitle or embedded subtitles that are not set to default in the metadata will not display. The old Emby Theater displayed all these subtitles so I am not sure what is the problem.

**Comment by LukePulverenti** [comment]
Can you compare to the old version? 

http://emby.media/community/index.php?/topic/29908-previous-version/

Thanks.

**Comment by justpig** [comment]
Thanks for getting back to me.
I have tested the old version on the same machines and the subtitles were displayed. Tried the same files again in the new version and they were not displayed.

**Comment by LukePulverenti** [comment]
can you provide a sample file because i am unable to reproduce this.

**Comment by LukePulverenti** [comment]
Also, what in-app settings have you changed from default, if any? Thanks.

**Comment by justpig** [comment]
Here is the requested file. I am using the default settings.


[Season 05.zip](https://github.com/MediaBrowser/Emby.Theater.Windows/files/92855/Season.05.zip)

**Comment by LukePulverenti** [comment]
Thank you. Please try again on 1.0.27.

**Comment by justpig** [comment]
Thanks Luke. Subtitles are working.
