### ISSUE TITLE
MadVR 24/60hz Refresh switching

### ISSUE THREAD

**Issue by xzener** [MediaBrowser/Emby.Theater.Windows#315]
Tested video backdrop/MadVR issue. The video backdrops are fine, the player changes to 24hz when pressing play regardless of having that option enabled/disabled (not sure if that is normal MadVR behavior). Stopping the movie, the refresh rate isn't switching back to 60hz as it should.  

EVR and EVR+ check ok as far as 24/60hz switching (w/ video backdrops).

**Comment by xzener** [comment]
This is a link to the forum bug reported. It has a log snip, hope it helps....http://emby.media/community/index.php?/topic/30190-bug-double-refresh-rate-switch-with-madvr/

**Comment by xzener** [comment]
Further testing with 1.0.28 today. 24hz/60hz switching is working now. This is with MadVR and auto switching enabled.

With MadVR and auto switching "disabled", when pressing play, 60hz switches to 24hz. But when stopping the movie, ET is stuck in 24hz. Have to close ET and reopen to fix. Rinse repeat.

**Comment by Jdiesel87** [comment]
The internal refresh rate switching works very well and switches to 24hz and back to 60hz after playback is stopped when madVR's switching is disabled. If possible, delaying the start of playback until after the internal refresh rate switching had completed should eliminate the need to use madVR's switching all together.

**Comment by njoak** [comment]
The internal rate switching does not work at all for me. With madVR switching (alone or together with the internal) it is better, but something seems to keep madVR from switching back when playback stops. Is maybe the video player not closed in a way that madVR notices?

Posted descriptions and logs here: http://emby.media/community/index.php?/topic/30541-bugrefresh-rate-switching-madvr/#entry294197
