### ISSUE TITLE
Recorded TV WTV Files Transcoded

### ISSUE THREAD

**Issue by denz2** [MediaBrowser/Emby.Theater.Windows#328]
I have updated to 1.0.38 and is still transcoding win 7 wmc wtv files at least that is what it is saying on the server page. I am running emby theater from the same pc as the emby server. The interlacing is horrible when you see the sample at least it is on my television with Nvidia graphics card using the latest driver. When I watch live tv it is saying direct playing same as if I watch a h.264 file and dvr-ms files But for wtv files it says transcoding and so does for m2ts file.

On my android emby app live tv is direct playing but everything else is transcoding even though I am connected through wifi.
 
Thank you

http://1drv.ms/1KeYq7C

[server-63589693546.txt](https://github.com/MediaBrowser/Emby.Theater.Windows/files/109719/server-63589693546.txt)
[transcode-65269a53-d12c-4c4e-a75d-2654e97b6f1f.txt](https://github.com/MediaBrowser/Emby.Theater.Windows/files/109722/transcode-65269a53-d12c-4c4e-a75d-2654e97b6f1f.txt)
[transcode-c3ac1844-7c9c-4272-905a-26b1385b914d.txt](https://github.com/MediaBrowser/Emby.Theater.Windows/files/109721/transcode-c3ac1844-7c9c-4272-905a-26b1385b914d.txt)

**Comment by LukePulverenti** [comment]
Closing this issue. If you add a wtv to your library it will direct stream fine. When using a live tv plugin it depends on media info and the app does not have enough media info to know that it is capable of direct playing it.
