### ISSUE TITLE
Lost focus returning to home screen

### ISSUE THREAD

**Issue by ebr11** [MediaBrowser/Emby.Theater.Windows#332]
Pretty sure this is related to the new refresh functionality on the home screen.

Select an item from latest movies and watch it to the end.  Return to home screen and the list is refreshed which removes the item you just watched.

Focus is nowhere.  Navigation sounds can be heard but you cannot gain focus on any item with the remote.

**Comment by denz2** [comment]
I am getting this regularly now the only way to get in focus is to plug in the mouse but then seems to lose focus again. The only button that causes the change in the screen is the back button. With the back button I can get to the settings menu and change values but can't get back to the main window. As Ebr said you can hear the navigation sounds as you press buttons on the remote.
