### ISSUE TITLE
Recordings thumbnail being replaced by movie poster which has different dimensions

### ISSUE THREAD

**Issue by denz2** [MediaBrowser/Emby.Theater.Windows#347]
It has happened only once so far but a recording thumbnail was replaced by the poster of the movie and it looked horrible because the dimensions were not the same as the other recordings it was three times smaller. I am not against thumbnails being replaced because most of the time the thumbnail is of the advertisement if it is being replaced it should be of the same dimension. 

Thanks

**Comment by LukePulverenti** [comment]
in the server turn off metadata for tv movies under live tv settings
