### ISSUE TITLE
Lack of useful info in the live tv detail screen 

### ISSUE THREAD

**Issue by denz2** [MediaBrowser/Emby.Theater.Windows#352]
When you go to upcoming programs it is missing the start time and end time and the channel logo and so are for all the other upcoming movies etc. The same for now playing it just has the todays date and the run time but when you don't know when the show started the run time is not of any help it would be more helpful and useful if it had the same as the upcoming programs start and end time and the channel logo. Example the same show in theater and WMC. WMC has far more useful information and logical information. 

![capture food](https://cloud.githubusercontent.com/assets/16771401/14584491/bcd8e6cc-047a-11e6-870e-258dc159b58a.PNG)
![capture 6000](https://cloud.githubusercontent.com/assets/16771401/14584493/c1558b06-047a-11e6-9b27-b099546c2d00.PNG)

**Comment by LukePulverenti** [comment]
More info has been added.
